### PR TITLE
New GR function, strip previous forks and combine loops

### PR DESCRIPTION
**Pull request by Bushstar**

### CODE REVIEW

**Comment by microguy** [comment]
I'm not sure why we have this 3-year-old pull request open from Bushstar.  But let's either merge or close this request.

**Comment by teddypaine** [comment]
Hello I am responding back to an email I received from you October 17th in
reference  to goldcoin I'm assuming.
If we can speak personally I'd like to ask a few questions pertaining to
the goldcoin crypto currency I've purchased and some questions involving
the goldcoin wallet associated with the platform/software in regards to
trading and the blockchain.
Thank you for your time.

**Comment by microguy** [comment]
> Hello I am responding back to an email I received from you October 17th in reference to goldcoin I'm assuming. If we can speak personally I'd like to ask a few questions pertaining to the goldcoin crypto currency I've purchased and some questions involving the goldcoin wallet associated with the platform/software in regards to trading and the blockchain. Thank you for your time.
>

Please use our discord. https://discord.me/goldcoin

**Review by microguy — APPROVED** [review]
Approving Bushstar's new GR function and merging.

This PR has been open for three years. Now that I'm helping maintain the Git, I wanted to get this off our plate. We can revert this commit before releasing 0.14.9 if there are any objections.

**Comment by Bushstar** [comment]
Please test this change with a full sync to double check the logic.

**Pull request merged**
